#!/bin/bash
# 司机工作台 - 一键部署到 Render.com
# 使用方法: bash deploy.sh

echo "🚗 司机工作台 - 部署到 Render"
echo "================================"
echo ""
echo "第一步：创建 Render 账号"
echo "  打开 https://render.com 用 GitHub 登录（免费，不需要信用卡）"
echo ""
echo "第二步：在 Render 创建一个新的 Web Service"
echo "  选择 'Build and deploy from a Git repository'"
echo "  选择这个项目的 Git 仓库"
echo "  或选择 'Public Git repository' 并填入仓库地址"
echo "  Runtime: Python 3"
echo "  Build Command: (留空)"
echo "  Start Command: python sync_server.py"
echo "  Free Instance Type: 选 'Free'"
echo "  点击 'Create Web Service'"
echo ""
echo "第三步：更新前端同步地址"
echo "  部署后会得到一个 URL 如 https://xxx.onrender.com"  
echo "  把这个 URL 更新到 index.html 中的 SYNC_SERVER 变量"
echo ""
echo "完成！管理员和司机都用同一个 Render URL，数据自动同步。"
echo ""
echo "如果不想用 Render，也可以用 Fly.io："
echo "  1. 安装: curl -L https://fly.io/install.sh | sh"
echo "  2. 登录: flyctl auth login"
echo "  3. 部署: flyctl launch (选择这个目录)"
